///
/// @file   proto_io.cpp
/// @Author Adam Saxen
/// @date   Oktober, 2016
/// @brief  Auto generated Wrapper class for NanoPb library
///
/// This class is autogenerated based on the proto file
///
#include "proto_io.h"

namespace ioant
{{

{messageClassesCpp}

ProtoIO* ProtoIO::CreateMessage(int message_type){{
    switch (message_type){{
{messageCreationCases}
    }}
}}

}}
