<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto

use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class Temperature extends \Google\Protobuf\Internal\Message
{
    private $temperature_celsius = 0.0;

    public function getTemperatureCelsius()
    {
        return $this->temperature_celsius;
    }

    public function setTemperatureCelsius($var)
    {
        GPBUtil::checkFloat($var);
        $this->temperature_celsius = $var;
    }

}

class Humidity extends \Google\Protobuf\Internal\Message
{
    private $procent = 0.0;

    public function getProcent()
    {
        return $this->procent;
    }

    public function setProcent($var)
    {
        GPBUtil::checkFloat($var);
        $this->procent = $var;
    }

}

class Mass extends \Google\Protobuf\Internal\Message
{
    private $grams = 0.0;

    public function getGrams()
    {
        return $this->grams;
    }

    public function setGrams($var)
    {
        GPBUtil::checkFloat($var);
        $this->grams = $var;
    }

}

class ElectricPower extends \Google\Protobuf\Internal\Message
{
    private $watt = 0.0;

    public function getWatt()
    {
        return $this->watt;
    }

    public function setWatt($var)
    {
        GPBUtil::checkFloat($var);
        $this->watt = $var;
    }

}

class GpsCoordinates extends \Google\Protobuf\Internal\Message
{
    private $longitude = 0.0;
    private $latitude = 0.0;
    private $height_ = 0.0;

    public function getLongitude()
    {
        return $this->longitude;
    }

    public function setLongitude($var)
    {
        GPBUtil::checkFloat($var);
        $this->longitude = $var;
    }

    public function getLatitude()
    {
        return $this->latitude;
    }

    public function setLatitude($var)
    {
        GPBUtil::checkFloat($var);
        $this->latitude = $var;
    }

    public function getHeight()
    {
        return $this->height_;
    }

    public function setHeight($var)
    {
        GPBUtil::checkFloat($var);
        $this->height_ = $var;
    }

}

class RunStepperMotorBasic extends \Google\Protobuf\Internal\Message
{
    private $direction = false;
    private $delay_between_steps = 0;
    private $number_of_step = 0;
    private $stepSize = 0;

    public function getDirection()
    {
        return $this->direction;
    }

    public function setDirection($var)
    {
        GPBUtil::checkBool($var);
        $this->direction = $var;
    }

    public function getDelayBetweenSteps()
    {
        return $this->delay_between_steps;
    }

    public function setDelayBetweenSteps($var)
    {
        GPBUtil::checkInt32($var);
        $this->delay_between_steps = $var;
    }

    public function getNumberOfStep()
    {
        return $this->number_of_step;
    }

    public function setNumberOfStep($var)
    {
        GPBUtil::checkInt32($var);
        $this->number_of_step = $var;
    }

    public function getStepSize()
    {
        return $this->stepSize;
    }

    public function setStepSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->stepSize = $var;
    }

}

class RunStepperMotor extends \Google\Protobuf\Internal\Message
{
    private $direction = false;
    private $rpm = 0.0;
    private $angle = 0.0;

    public function getDirection()
    {
        return $this->direction;
    }

    public function setDirection($var)
    {
        GPBUtil::checkBool($var);
        $this->direction = $var;
    }

    public function getRpm()
    {
        return $this->rpm;
    }

    public function setRpm($var)
    {
        GPBUtil::checkFloat($var);
        $this->rpm = $var;
    }

    public function getAngle()
    {
        return $this->angle;
    }

    public function setAngle($var)
    {
        GPBUtil::checkFloat($var);
        $this->angle = $var;
    }

}

class RunDcMotor extends \Google\Protobuf\Internal\Message
{
    private $direction = false;
    private $rpm = 0.0;

    public function getDirection()
    {
        return $this->direction;
    }

    public function setDirection($var)
    {
        GPBUtil::checkBool($var);
        $this->direction = $var;
    }

    public function getRpm()
    {
        return $this->rpm;
    }

    public function setRpm($var)
    {
        GPBUtil::checkFloat($var);
        $this->rpm = $var;
    }

}

class BootInfo extends \Google\Protobuf\Internal\Message
{
    private $reboot_reason = '';
    private $program_size = 0;
    private $ipaddress = '';

    public function getRebootReason()
    {
        return $this->reboot_reason;
    }

    public function setRebootReason($var)
    {
        GPBUtil::checkString($var, True);
        $this->reboot_reason = $var;
    }

    public function getProgramSize()
    {
        return $this->program_size;
    }

    public function setProgramSize($var)
    {
        GPBUtil::checkUint32($var);
        $this->program_size = $var;
    }

    public function getIpaddress()
    {
        return $this->ipaddress;
    }

    public function setIpaddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->ipaddress = $var;
    }

}

class MessageTypes
{
    const TYPE_TEMPERATURE = 0;
    const TYPE_HUMIDITY = 1;
    const TYPE_MASS = 2;
    const TYPE_ELECTRIC_POWER = 3;
    const TYPE_GPS_COORDINATES = 4;
    const TYPE_RUN_STEPPER_MOTOR_BASIC = 5;
    const TYPE_RUN_STEPPER_MOTOR = 6;
    const TYPE_RUN_DC_MOTOR = 7;
    const TYPE_BOOT_INFO = 8;
}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0af2050a0e6d657373616765732e70726f746f222a0a0b54656d70657261" .
    "74757265121b0a1374656d70657261747572655f63656c73697573180120" .
    "012802221b0a0848756d6964697479120f0a0770726f63656e7418012001" .
    "280222150a044d617373120d0a056772616d73180120012802221d0a0d45" .
    "6c656374726963506f776572120c0a047761747418012001280222460a0e" .
    "477073436f6f7264696e6174657312110a096c6f6e676974756465180120" .
    "01280212100a086c61746974756465180220012802120f0a076865696768" .
    "745f18032001280222700a1452756e537465707065724d6f746f72426173" .
    "696312110a09646972656374696f6e180120012808121b0a1364656c6179" .
    "5f6265747765656e5f737465707318022001280512160a0e6e756d626572" .
    "5f6f665f7374657018032001280512100a087374657053697a6518042001" .
    "280522400a0f52756e537465707065724d6f746f7212110a096469726563" .
    "74696f6e180120012808120b0a0372706d180220012802120d0a05616e67" .
    "6c65180320012802222c0a0a52756e44634d6f746f7212110a0964697265" .
    "6374696f6e180120012808120b0a0372706d180220012802224a0a08426f" .
    "6f74496e666f12150a0d7265626f6f745f726561736f6e18012001280912" .
    "140a0c70726f6772616d5f73697a6518022001280d12110a096970616464" .
    "726573731803200128092ae2010a0c4d657373616765547970657312140a" .
    "10545950455f54454d5045524154555245100012110a0d545950455f4855" .
    "4d49444954591001120d0a09545950455f4d415353100212170a13545950" .
    "455f454c4543545249435f504f574552100312180a14545950455f475053" .
    "5f434f4f5244494e41544553100412200a1c545950455f52554e5f535445" .
    "505045525f4d4f544f525f42415349431005121a0a16545950455f52554e" .
    "5f535445505045525f4d4f544f52100612150a11545950455f52554e5f44" .
    "435f4d4f544f52100712120a0e545950455f424f4f545f494e464f100862" .
    "0670726f746f33"
));

